# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=30)),
                ('imagen_mascota', models.ImageField(upload_to='img_mascota')),
                ('tamanio', models.PositiveIntegerField(choices=[(0, 'Peque\xf1o'), (1, 'Mediano'), (2, 'Grande')])),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.PositiveIntegerField(choices=[(0, 'Macho'), (1, 'Hembra')])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='tipo_animal',
            options={'ordering': ('id',), 'verbose_name': 'Tipo Animal', 'verbose_name_plural': 'Tipos de animales'},
        ),
        migrations.AddField(
            model_name='mascota',
            name='fk_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascota.Tipo_Animal'),
        ),
    ]
